#!/bin/bash

for file in files/*.txt; do
    
    first_char=$(echo "$(basename "$file")" | head -c 1)

    if [[ "$first_char" =~ [A-Z] ]]; then
        first_char=$(echo "$first_char" | tr '[:upper:]' '[:lower:]')
    fi

    mv $file ./"$first_char"

done